// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Button from "./components/Button/Button.bs.js";
import * as GlobalStyles from "./lib/GlobalStyles.bs.js";

GlobalStyles.includeStyle(undefined);

function App(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  return React.createElement("div", undefined, React.createElement("h1", undefined, "hello rescript"), React.createElement("h2", undefined, match[0]), React.createElement(Button.make, {
                  children: "increment",
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (prev) {
                                    return prev + 1 | 0;
                                  }));
                    })
                }), React.createElement(Button.make, {
                  children: "decrease",
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (prev) {
                                    return prev - 1 | 0;
                                  }));
                    })
                }));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
